name: Get commit  version

# TODO: implement commit description validation

inputs:
  repo_dir:
    required: true
    type: string
  commit_sha:
    required: false
    type: string
outputs:
  commit_version:
    description: "Version extracted from commit (head if commit_sha was not provided or is empty)"
    value: ${{ format('{0}{1}', steps.read_head_version.outputs.head_version, steps.read_commit_version.outputs.commit_version) }}
  commit_tag:
    description: "Tag extracted from commit (head if commit_sha was not provided or is empty)"
    value: ${{ format('{0}{1}', steps.read_head_version.outputs.head_tag, steps.read_commit_version.outputs.commit_tag) }}
  commit_action:
    description: "Action extracted from commit (head if commit_sha was not provided or is empty). Currently: r - release"
    value: ${{ format('{0}{1}', steps.read_head_version.outputs.head_action, steps.read_commit_version.outputs.commit_action) }}

runs:
  using: "composite"

  steps:
    - id: read_head_version
      shell: bash
      if: ${{ inputs.commit_sha == '' }}
      run: |
        cd "${{ inputs.repo_dir }}"

        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          CHANGE_MSG="${{ github.event.pull_request.title }}"
          CHANGE_TAGS="$CHANGE_MSG"
        else
          COMMIT_SHA="${{ github.sha }}"
          CHANGE_MSG=$(git log -1 $COMMIT_SHA --pretty=format:"%s")
          CHANGE_TAGS=$(git log -1 $COMMIT_SHA --pretty=format:"%d")
        fi

        head_version=$(echo "$CHANGE_MSG" | grep -Po '\[\K([\d.]+)\]' | grep -Po '[^\]]+' || true)
        head_action=$(echo "$CHANGE_MSG" | grep -Po '\[([\d.]+)\]\[\K[\w]+\]' | grep -Po '[^\]]+' || true)
        head_tag=$(echo "$CHANGE_TAGS" | grep -Po 'tag: \K\d+\.\d+\.\d+' || true)

        # Output values
        echo "head_version=$head_version" >> $GITHUB_OUTPUT
        echo "head_tag=$head_tag" >> $GITHUB_OUTPUT
        echo "head_action=$head_action" >> $GITHUB_OUTPUT
    - if: ${{ inputs.commit_sha == '' }}
      shell: bash
      run: |
        echo "VERSION: '${{ steps.read_head_version.outputs.head_version }}'"
        echo "TAG: '${{ steps.read_head_version.outputs.head_tag }}'"
        echo "ACTION: '${{ steps.read_head_version.outputs.head_action }}'"


    - id: read_commit_version
      shell: bash
      if: ${{ inputs.commit_sha != '' }}
      run: |
        cd "${{ inputs.repo_dir }}"
        echo "commit_version=$(git log -1 ${{ inputs.commit_sha }} --pretty=format:"%s" | grep -Po '\[\K([\d.]+)\]' | grep -Po '[^\]]+')" >> $GITHUB_OUTPUT
        echo "commit_tag=$(git log -1 ${{ inputs.commit_sha }} --pretty=format:"%d" | grep -Po 'tag: \K\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT
        echo "commit_action=$(git log -1 ${{ inputs.commit_sha }} --pretty=format:"%s" | grep -Po '\[([\d.]+)\]\[\K[\w]+\]' | grep -Po '[^\]]+')" >> $GITHUB_OUTPUT
    - if: ${{ inputs.commit_sha != '' }}
      shell: bash
      run: |
        echo "VERSION: '${{ steps.read_commit_version.outputs.commit_version }}'"
        echo "TAG: '${{ steps.read_commit_version.outputs.commit_tag }}'"
        echo "ACTION: '${{ steps.read_commit_version.outputs.commit_action }}'"
