name: "SCA"

on:
  workflow_call:
    inputs:
      artifact_name:
        description: "Name of build artifact produced by build.yml"
        required: false
        type: string
        default: "build-artifacts-ubuntu"
      artifacts_dir:
        description: "Directory where build artifacts will be downloaded"
        required: false
        type: string
        default: "build"
  workflow_dispatch:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  codeql:
    name: "CodeQL"
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name || 'build-artifacts-ubuntu' }}
          path: ${{ github.workspace }}/${{ inputs.artifacts_dir || 'build' }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp
          build-mode: none

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: /language:cpp

  misra:
    name: "MISRA-C-2012"
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name || 'build-artifacts-ubuntu' }}
          path: ${{ github.workspace }}/${{ inputs.artifacts_dir || 'build' }}

      - name: Install cppcheck
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: cppcheck
          version: 1.0

      - name: Run MISRA check
        run: |
          cppcheck --addon=${{ github.workspace }}/scripts/cppcheck/misra.json \
            --enable=warning,performance,portability,information \
            --inline-suppr \
            --xml \
            --suppressions-list=${{ github.workspace }}/scripts/cppcheck/cppcheck_suppress.txt \
            --project=${{ github.workspace }}/${{ inputs.artifacts_dir || 'build' }}/compile_commands.json \
            -DSTL_AVAILABLE -D__GNU__=1 -D__LITTLE_ENDIAN__ -D__GNUC__ 2> ${{ github.workspace }}/sca_misra.txt

      - name: Validate cppcheck report
        run: |
          ${{ github.workspace }}/scripts/cppcheck/cppcheck_review.py ${{ github.workspace }}/sca_misra.txt

  coverity:
    name: "Coverity"
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    env:
      COVERITY_NAME: 'Igor Krechetov'
      COVERITY_VERSION: 'cov-analysis-linux64-2023.6.2'
      COVERITY_PROJECT_DESCRIPTION: 'Reusable GitHub workflows for HSM projects.'
      COVERITY_PROJECT: 'igor-krechetov/hsm-github-workflows'
      COVERITY_PROJECT_URL: 'igor-krechetov%2Fhsm-github-workflows'
      BUILDCMD: 'cmake --build ./build --parallel 2 --config Release'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '11'

      - name: Cache Coverity
        id: cache-coverity
        uses: actions/cache@v4
        with:
          path: ~/coverity
          key: coverity-tool
          restore-keys: coverity-tool

      - name: Coverity Download & Install
        if: ${{ steps.cache-coverity.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p ~/download
          mkdir -p ~/coverity
          wget https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=$COVERITY_PROJECT_URL" -O ~/download/coverity_tool.tgz
          cd ~/coverity
          tar -xvzf ~/download/coverity_tool.tgz

      - name: Configure project build
        uses: igor-krechetov/hsm-github-workflows/.github/actions/build_helper@feature/hsmcpp-ci-integration
        with:
          platform: posix
          build_type: ${{ env.BUILD_TYPE }}
          src_dir: ${{ github.workspace }}
          build_dir: ${{ github.workspace }}/build
          build_tests: 'OFF'
          build_examples: 'ON'
          only_configure: true

      - name: Coverity Full Scan
        run: |
          export PATH=$PATH:~/coverity/$COVERITY_VERSION/bin/
          cov-configure --config ./coverity.xml --template --compiler c++ --comptype gcc --xml-option=skip_file:"/usr/include/.*" --xml-option=skip_file:".*/thirdparty/.*"
          python3 ./scripts/coverity/coverity-submit.py -u "$COVERITY_NAME" -b "${{ github.sha }}" -config ./coverity.xml -t "$COVERITY_PROJECT_DESCRIPTION" -p "$COVERITY_PROJECT" -pu "$COVERITY_PROJECT_URL" -token "${{ secrets.COVERITY_TOKEN }}" -email "${{ secrets.COVERITY_EMAIL }}" -build "$BUILDCMD"
